# R Package Requirements for Nested LOOCV with VSURF and Elastic Net
# Install these packages before running the main script

# Core packages
install.packages("VSURF")
install.packages("caret")
install.packages("glmnet")
install.packages("tidyverse")
install.packages("recipes")
install.packages("ModelMetrics")
install.packages("yardstick")
install.packages("MLeval")
install.packages("prg")
install.packages("CalibrationCurves")
install.packages("dcurves")
install.packages("readxl")
install.packages("statip")
install.packages("pheatmap")
install.packages("janitor")
install.packages("doParallel")

# Load all packages to check if they're working
library(caret)
library(tidyverse)
library(ModelMetrics)
library(recipes)
library(glmnet)
library(yardstick)
library(MLeval)    
library(doParallel)
library(VSURF)
library(prg)
library(CalibrationCurves)
library(dcurves)
library(readxl)
library(statip)
library(pheatmap)
library(VIM)
library(janitor)

cat("All packages loaded successfully!\n")